name: CI

on: 
  push:
  workflow_dispatch:

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build archive
      run: xcodebuild \
           -scheme KeePassium \
           -configuration Release archive \
           -archivePath ./KeePassium.xcarchive
    - name: Build app
      run: xcodebuild \
           -exportArchive \
           -archivePath ./KeePassium.xcarchive \
           -exportPath . \
           -exportOptionsPlist ./KeePassium.xcarchive/Info.plist
     
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        path: ./*.ipa
