name: CI

on: 
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: GitHub Action for SwiftLint
        uses: norio-nomura/action-swiftlint@3.2.1
        with:
          args: --strict

  build:
    needs: test
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build Projects
      run: xcodebuild build -project KeePassium.xcodeproj -scheme KeePassium -sdk iphoneos -configuration Release CODE_SIGNING_ALLOWED=NO
    - name: Build archive
      run: xcodebuild build -project KeePassium.xcodeproj -scheme KeePassium -sdk iphoneos -configuration Release -archivePath KeePassium.xcarchive CODE_SIGNING_ALLOWED=NO
    - name: Build app
      run: xcodebuild -exportArchive -archivePath ./KeePassium.xcarchive -exportPath . -exportOptionsPlist ./KeePassium.xcarchive/Info.plist
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        path: ./*.ipa
